[package]
name = "rust-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
sha1 = "0.11.0-pre.4"
tokio = { version = "1.41.1", features = ["full"] }
log = "0.4.22"
env_logger = "0.11.5"
