# beacon variables can be omitted if running with --skip-join flag
beacon_node_address: "127.0.0.1:8081"
beacon_node_key: key # Must be K bytes, (K*2 hex characters)
# explicit node port can be omitted, in that case an ephemeral port will be used
node_port: 8081
cache_file_path: "cache.json"
storage_path: "/path/to/storage"
ip_address: "local" # "public" or "loopback" or "local"